### PR TITLE
Satisfactory Update

### PR DESCRIPTION
**Pull request by Niborian**
I dont use this so It has not been tested I just changed versions to pull:

image:
  repository: wolveix/satisfactory-server
  pullPolicy: IfNotPresent
  tag: v1@sha256:889a4735c2fec437ed1c75a27d45415a31d40faac6a68336cc88a98e3b2f9316

### CODE REVIEW

**Comment by Niborian** [comment]
@v3DJG6GL Could you look at all the requests? 😊😅

**Comment by ikiris** [comment]
You should drop this one I've got a proper or going in for the changes made with 1.0 release

**Comment by Niborian** [comment]
> You should drop this one I've got a proper or going in for the changes made with 1.0 release


okay... could you provide any specific reasons for this recommendation?

I could change the digest to bump the version to v1.8.4 if needed since this isn’t approved yet. I noticed that the v1 tag seems to function like "latest," but I'm not entirely sure about this. Is there a reason not to use the v1 tag?
thanks 😊

**Comment by ikiris** [comment]
> > You should drop this one I've got a proper or going in for the changes made with 1.0 release
> 
> okay... could you provide any specific reasons for this recommendation?
> 
> I could change the digest to bump the version to v1.8.4 if needed since this isn’t approved yet. I noticed that the v1 tag seems to function like "latest," but I'm not entirely sure about this. Is there a reason not to use the v1 tag? thanks 😊

You can go look at my pull request. The app changed more than just version. The exposed api contract did as well.

**Comment by Niborian** [comment]
@ikiris  I dont quite get what you mean by "The exposed api contract did as well." and what that has todo and where you changed that, and ik it changed by more than one version... I updated to v1@digest... and v1 was updated so if I update the digest to the newer one I would basicly have version 1.8.4  (released 13h ago), Im just curious to what I should have done that I dident😅

**Pull request closed without merging**
